//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDeneme.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Tbl_Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Blog()
        {
            this.Tbl_BlogYorum = new HashSet<Tbl_BlogYorum>();
        }
    
        public int ID { get; set; }
        public string RESIM { get; set; }
        public string BASLIK { get; set; }

        [AllowHtml]
        public string ICERIK { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string YAZAR { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string BILGILENDIRME { get; set; }
    
        public virtual Tbl_BlogKategori Tbl_BlogKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BlogYorum> Tbl_BlogYorum { get; set; }
    }
}
