//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDeneme.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SosyalMedya
    {
        public byte ID { get; set; }
        public Nullable<byte> IKON { get; set; }
        public string LINK { get; set; }
        public string AD { get; set; }
    
        public virtual Tbl_SosyalMedyaIkon Tbl_SosyalMedyaIkon { get; set; }
    }
}
