//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDeneme.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SosyalMedyaIkon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SosyalMedyaIkon()
        {
            this.Tbl_SosyalMedya = new HashSet<Tbl_SosyalMedya>();
        }
    
        public byte ID { get; set; }
        public string IKON { get; set; }
        public string AD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SosyalMedya> Tbl_SosyalMedya { get; set; }
    }
}
